(() => {
'use strict';
const CACHE='news-live-cache',QUICK='news-article-summaries-v8',AI='news-verified-ai-summaries-v9138';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},clean=v=>String(v??'').replace(/\s+/g,' ').trim(),norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,' ').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const articles=()=>{const c=read(CACHE,{});return Array.isArray(c.articles)?c.articles:[]};let last='';const jobs=new Map();
const good=v=>{const t=clean(v);return t.length>=55&&!/résumé (?:détaillé )?momentanément indisponible|résumé ia indisponible|résumé indisponible|en cours de préparation/i.test(t)};
function article(modal){if(last){const a=articles().find(x=>String(x.id)===last);if(a)return a}const h=norm(modal.querySelector('.quick-summary-head h2')?.textContent);return articles().find(a=>{const t=norm(a.title);return h&&(t.includes(h)||h.includes(t))})}
function cache(a,sum,ai){if(!a?.id||!good(sum))return;const key=`article:${a.id}`,q=read(QUICK,{});q[key]={summary:clean(sum),ai:!!ai,unavailable:false,savedAt:Date.now()};write(QUICK,Object.fromEntries(Object.entries(q).slice(-180)));if(ai){const v=read(AI,{});v[key]={summary:clean(sum),savedAt:Date.now()};write(AI,Object.fromEntries(Object.entries(v).slice(-180)))}}
function show(m,text,status,ai=false){const box=m.querySelector('[data-quick-summary-text]');if(box)box.textContent=clean(text);let s=m.querySelector('.quick-summary-status-v9138');if(!s&&box){s=document.createElement('div');box.before(s)}if(s){s.className=`quick-summary-status-v9138 ${ai?'ai':'source'}`;s.textContent=status}m.dataset.rescueText=clean(text);m.dataset.rescueStatus=status;m.dataset.rescueAi=ai?'1':'0'}
async function json(url,opt){try{const r=await fetch(url,opt);return r.ok?await r.json():null}catch{return null}}
async function rescue(m){const a=article(m);if(!a?.id||jobs.has(String(a.id)))return;const id=String(a.id),job=(async()=>{await new Promise(r=>setTimeout(r,1350));if(!m.isConnected)return;const box=m.querySelector('[data-quick-summary-text]');if(good(box?.textContent))return;const raw=clean(a.summary),context=good(raw)?raw:clean(a.title),payload={mode:'article',article:{url:a.url,title:clean(a.title),summary:context,source:clean(a.source)}};const g=await json('/api/article-summary-groq?v=17&intent=rescue',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify(payload)});let sum=clean(g?.summary);if(m.isConnected&&!g?.unavailable&&good(sum)){const ai=g?.ai===true||/groq/i.test(String(g?.provider||''));cache(a,sum,ai);show(m,sum,ai?'Résumé IA':'Résumé',ai);return}const s=await json('/api/article-summary-smart?v=5',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({article:payload.article})});const recovered=clean(s?.text);if(!m.isConnected||!s?.ok||!good(recovered))return;const g2=await json('/api/article-summary-groq?v=17&intent=recovered',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({mode:'article',article:{...payload.article,summary:recovered}})});sum=clean(g2?.summary);if(m.isConnected&&!g2?.unavailable&&good(sum)){const ai=g2?.ai===true||/groq/i.test(String(g2?.provider||''));cache(a,sum,ai);show(m,sum,ai?'Résumé IA':'Résumé',ai);return}cache(a,recovered,false);show(m,recovered,'Résumé vérifié',false)})().finally(()=>jobs.delete(id));jobs.set(id,job)}
function polish(){const m=document.querySelector('.quick-summary-backdrop');if(!m)return;m.querySelector('.quick-topic-feedback')?.remove();const h=m.querySelector('.quick-feedback-help');if(h)h.innerHTML='<strong>Choix sur cet article</strong>';for(const n of m.querySelectorAll('h2,h3,strong,p,div')){const t=norm(n.textContent);if((t==='ne plus afficher un theme ou un mot'||t==='ne plus afficher un theme ou mot')&&n.children.length<3)n.classList.add('center-exclusion-v9138')}if(m.dataset.rescueText&&!good(m.querySelector('[data-quick-summary-text]')?.textContent))show(m,m.dataset.rescueText,m.dataset.rescueStatus||'Résumé',m.dataset.rescueAi==='1');rescue(m)}
document.addEventListener('pointerdown',e=>{const c=e.target.closest?.('.article-card[data-article]');if(c?.dataset.article)last=String(c.dataset.article)},true);
new MutationObserver(polish).observe(document.body,{childList:true,subtree:true});setTimeout(polish,0);
const s=document.createElement('style');s.textContent=`
.quick-topic-feedback{display:none!important}.quick-feedback-help{text-align:center!important;margin:18px 0 8px!important;font-size:16px!important;line-height:1.2!important}.quick-feedback-help strong{font-size:16px!important;font-weight:900!important;color:#3b3448!important}.quick-feedback-secondary{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;margin-top:8px!important}.quick-feedback-secondary .quick-feedback-tile{min-height:48px!important;padding:8px 9px!important;align-items:center!important;border-radius:12px!important}.quick-feedback-secondary .quick-feedback-symbol{width:23px!important;height:23px!important;flex-basis:23px!important;font-size:15px!important}.quick-feedback-secondary .quick-feedback-tile strong{margin:0!important;font-size:11.5px!important}.quick-feedback-secondary .quick-feedback-tile small{display:none!important}.center-exclusion-v9138{text-align:center!important;width:100%!important;font-weight:850!important}
`;document.head.appendChild(s);
})();
