import { preparedVisualUrl, sourceTileUrl } from './services/article-visuals.js?v=92.04';
const state=new WeakMap(),MAX_ACTIVE=8,RETRY_AFTER=9000;let active=0,generation=0,queue=[],scheduled=false;
function readArticles(){try{const p=JSON.parse(localStorage.getItem('news-live-cache')||'{}');return Array.isArray(p.articles)?p.articles:[]}catch{return[]}}function articlesById(){return new Map(readArticles().map(a=>[String(a?.id||''),a]))}
function preload(url,timeout=2400,priority='auto'){return new Promise(resolve=>{if(!url)return resolve(false);const im=new Image();let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(t);im.onload=im.onerror=null;resolve(ok)};const t=setTimeout(()=>finish(false),timeout);im.onload=()=>finish(im.naturalWidth>1);im.onerror=()=>finish(false);im.decoding='async';try{im.fetchPriority=priority}catch{};im.src=url;if(im.complete)finish(im.naturalWidth>1)})}
function mark(img,ok){img.classList.remove('image-pending-v9184');img.classList.toggle('image-ready-v9184',ok);img.classList.toggle('image-failed-v9184',!ok);img.dataset.imageSequenceDone='1'}
async function resolveVisual(article,priority){const tile=sourceTileUrl(article),wanted=preparedVisualUrl(article);if(wanted&&wanted!==tile){const ok=await preload(wanted,priority==='high'?1800:2400,priority);if(ok)return{url:wanted,ok:true}}if(tile){await preload(tile,1000,priority);return{url:tile,ok:false}}return{url:wanted||'',ok:false}}
function priority(card,index){const r=card.getBoundingClientRect();if(r.bottom>=0&&r.top<=innerHeight)return index;if(r.top>innerHeight)return 500+Math.round(r.top);return 300+index}
function pump(){queue.sort((a,b)=>a.priority-b.priority);while(active<MAX_ACTIVE&&queue.length){const job=queue.shift();if(!job.card?.isConnected)continue;active++;run(job).finally(()=>{active--;pump()})}}
async function run(job){const{card,article,token}=job;if(token!==generation)return;const img=card.querySelector('img.article-image');if(!img)return;const high=job.priority<500,visual=await resolveVisual(article,high?'high':'auto');if(token!==generation||!card.isConnected)return;if(visual.url){img.loading='eager';img.decoding='async';try{img.fetchPriority=high?'high':'auto'}catch{};if(img.src!==new URL(visual.url,location.href).href)img.src=visual.url}mark(img,visual.ok);state.set(card,{status:visual.ok?'done':'failed',at:Date.now()})}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;const byId=articlesById(),now=Date.now();document.querySelectorAll('.article-card[data-article]').forEach((card,index)=>{const r=card.getBoundingClientRect();if(!(index<36||(r.bottom>=-250&&r.top<=innerHeight*3.5)))return;const prev=state.get(card);if(prev?.status==='loading'||prev?.status==='done'||(prev?.status==='failed'&&now-prev.at<RETRY_AFTER))return;const article=byId.get(String(card.dataset.article||''));if(!article)return;const img=card.querySelector('img.article-image');if(img){img.classList.add('image-pending-v9184');img.loading='eager';try{img.fetchPriority=r.top<=innerHeight*1.5?'high':'auto'}catch{}}state.set(card,{status:'loading',at:now});queue.push({card,article,priority:priority(card,index),token:generation})});pump()})}
function resetForRender(){generation++;queue=[];schedule()}const app=document.getElementById('app');if(app)new MutationObserver(schedule).observe(app,{childList:true,subtree:true});window.addEventListener('news:stable-render',resetForRender);window.addEventListener('pageshow',schedule);window.addEventListener('online',()=>{generation++;queue=[];schedule()});let sf=0;window.addEventListener('scroll',()=>{if(sf)return;sf=requestAnimationFrame(()=>{sf=0;schedule()})},{passive:true});schedule();