plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wokgui.monactualite'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wokgui.monactualite'
        minSdk 26
        targetSdk 35
        versionCode 84
        versionName '84.91.95'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
        }
    }
}
